---
- name: Update cache repositories and install Nginx
  package:
    name: nginx
    state: present

- name: Change nginx directory permission
  file:
    path: /etc/nginx/nginx.conf
    mode: 0750

- name: start nginx
  service:
    name: nginx
    state: started
